# Generated by Django 4.2 on 2024-01-14 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("filer", "0017_image__transparent"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=64)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="catalog.category",
                    ),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Modification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Product title (without model)"
                    ),
                ),
                ("slug", models.SlugField()),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "discounted_price",
                    models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "image_opaque",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        help_text="With an opaque background. (used by Yandex Direct)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_with_image_opaque",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.model"
                    ),
                ),
                (
                    "modification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.modification"
                    ),
                ),
                (
                    "schema",
                    filer.fields.file.FilerFileField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_with_schema",
                        to="filer.file",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
                "unique_together": {("model", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ProductProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_properties",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("power", "Мощность"),
                            ("beam", "Световой поток"),
                            ("color_index", "Индекс цветопередачи"),
                            ("color_temperature", "Цветовая температура"),
                            ("body_color", "Цвет корпуса"),
                            ("frame_color", "Цвет рамки"),
                            ("cover_color", "Цвет накладки"),
                            ("dimming", "Управление яркостью"),
                            ("beam_angle", "Угол рассеивания"),
                            ("protection", "Влагозащита"),
                            ("size", "Размер"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(max_length=32)),
                ("color_code", models.CharField(blank=True, max_length=32)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="catalog.propertygroup",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="properties",
                        through="catalog.ProductProperty",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="productproperty",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_properties",
                to="catalog.property",
            ),
        ),
        migrations.CreateModel(
            name="ProductFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=32)),
                (
                    "file",
                    filer.fields.file.FilerFileField(
                        on_delete=django.db.models.deletion.CASCADE, to="filer.file"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="category",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="catalog.group",
            ),
        ),
    ]
