# Generated by Django 4.2 on 2024-01-24 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_category_slug_group_slug_alter_product_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="image",
        ),
    ]
