# Generated by Django 4.2 on 2024-01-24 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_remove_model_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="schema",
            new_name="scheme",
        ),
    ]
