# Generated by Django 4.2 on 2024-01-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("pre_title", models.CharField(blank=True, max_length=256)),
                ("title", models.CharField(blank=True, max_length=256)),
                ("subtitle", models.CharField(blank=True, max_length=256)),
                ("description", models.TextField(blank=True)),
                (
                    "image_position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("inner_title", models.CharField(max_length=128)),
                ("title", models.CharField(blank=True, max_length=128)),
                ("link", models.CharField(blank=True, max_length=128)),
                ("link_text", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("inner_title", models.CharField(max_length=64)),
                ("title", models.CharField(blank=True, max_length=64)),
                ("slug", models.SlugField()),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ModelCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=64)),
                ("text", models.TextField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_cards",
                        to="content.contentblock",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_cards",
                        to="catalog.model",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="contentblock",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="content.page",
            ),
        ),
        migrations.CreateModel(
            name="Button",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("text", models.CharField(max_length=64)),
                ("link", models.CharField(blank=True, max_length=128)),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="content.banner",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="banner",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banners",
                to="content.contentblock",
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="image",
            field=filer.fields.image.FilerImageField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banners",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
    ]
