# Generated by Django 4.2 on 2024-01-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="mobile_image",
            field=models.BooleanField(
                default=True, help_text="Show image on mobile devices (screens < 1024px)"
            ),
        ),
        migrations.AddField(
            model_name="contentblock",
            name="form",
            field=models.CharField(
                blank=True,
                choices=[("CONSULT", "Get consultation form"), ("CATALOG", "Get catalog form")],
            ),
        ),
    ]
