# Generated by Django 4.2 on 2023-12-28 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="button",
            name="banner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buttons",
                to="content.banner",
            ),
        ),
    ]
