# Generated by Django 4.2 on 2024-01-07 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("content", "0002_banner_mobile_image_contentblock_form"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelcard",
            options={"ordering": ["ordering", "-updated"]},
        ),
        migrations.AlterField(
            model_name="modelcard",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="content.contentblock",
            ),
        ),
        migrations.CreateModel(
            name="ProjectCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=64)),
                ("text", models.TextField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="content.contentblock",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_cards",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["ordering", "-updated"],
            },
        ),
    ]
