# Generated by Django 4.2 on 2023-12-28 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("adaptive_images", "0001_initial"),
        ("catalog", "0001_initial"),
        ("content", "0002_alter_button_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="banners",
                to="adaptive_images.adaptiveimage",
            ),
        ),
        migrations.AlterModelTable(
            name="banner",
            table=None,
        ),
        migrations.AlterModelTable(
            name="button",
            table=None,
        ),
        migrations.AlterModelTable(
            name="contentblock",
            table=None,
        ),
        migrations.AlterModelTable(
            name="page",
            table=None,
        ),
        migrations.CreateModel(
            name="ModelCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=64)),
                ("text", models.TextField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_cards",
                        to="adaptive_images.adaptiveimage",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_cards",
                        to="catalog.model",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
    ]
