# Generated by Django 4.2 on 2024-01-07 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("projects", "0003_remove_feedback_is_on_main_page"),
        ("content", "0003_alter_modelcard_options_alter_modelcard_block_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelcard",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modelcards",
                to="catalog.model",
            ),
        ),
        migrations.AlterField(
            model_name="projectcard",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projectcards",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="FeedbackCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="content.contentblock",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbackcards",
                        to="projects.feedback",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
    ]
