# Generated by Django 4.2 on 2024-01-07 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("content", "0004_alter_modelcard_model_alter_projectcard_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelcard",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="projectcard",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=128)),
                ("text", models.TextField()),
                ("slug", models.SlugField(unique=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="content.contentblock",
                    ),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pubcitationcards",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
    ]
