# Generated by Django 4.2 on 2024-01-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_alter_modelcard_title_alter_page_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcard",
            name="arrow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectcard",
            name="arrow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publication",
            name="arrow",
            field=models.BooleanField(default=False),
        ),
    ]
