# Generated by Django 4.2 on 2024-01-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_banner_addrees_banner_email_banner_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentblock",
            name="form",
        ),
        migrations.AddField(
            model_name="contentblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("CONSULT_FORM", "Get consultation form"),
                    ("CATALOG_FORM", "Get catalog form"),
                    ("BANNERS", "Simple banners"),
                    ("WIDE_BANNERS", "Wide banners"),
                ],
                default="BANNERS",
            ),
        ),
    ]
