# Generated by Django 4.2 on 2024-01-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_remove_contentblock_form_contentblock_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="type",
            field=models.CharField(
                choices=[
                    ("SIMPLE", "Simple banner"),
                    ("HERO", "Hero banner"),
                    ("TAB", "Tab banner (4 images)"),
                ],
                default="SIMPLE",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("CONSULT_FORM", "Get consultation form"),
                    ("CATALOG_FORM", "Get catalog form"),
                    ("BANNERS", "Simple banners (inside the container)"),
                    ("WIDE_BANNERS", "Wide banners (the full width of the screen)"),
                ],
                default="BANNERS",
            ),
        ),
    ]
