# Generated by Django 4.2 on 2024-01-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_banner_type_alter_contentblock_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="type",
            field=models.CharField(
                choices=[
                    ("SIMPLE", "Simple banner"),
                    ("HERO", "Hero banner"),
                    ("TAB", "Tab banner (4 images)"),
                    ("CONSULTANT", "Consultant banner"),
                ],
                default="SIMPLE",
                max_length=32,
            ),
        ),
    ]
