# Generated by Django 4.2 on 2024-01-08 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("content", "0010_alter_banner_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="button",
            old_name="text",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="modelcard",
            old_name="text",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="projectcard",
            old_name="text",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="publication",
            old_name="text",
            new_name="description",
        ),
        migrations.CreateModel(
            name="Tab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ordering", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to="content.banner",
                    ),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-updated"],
                "abstract": False,
            },
        ),
    ]
