# Generated by Django 4.2 on 2023-12-26 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("internal_name", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[("desktop", "Desktop"), ("mobile", "Mobile")], max_length=7
                    ),
                ),
                ("max_width", models.PositiveSmallIntegerField()),
                ("max_height", models.PositiveSmallIntegerField()),
                ("quality", models.PositiveSmallIntegerField(default=80)),
            ],
            options={
                "db_table": "image_preset",
            },
        ),
        migrations.CreateModel(
            name="AdaptiveImageSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "is_image_compress",
                    models.BooleanField(default=False, verbose_name="compress images?"),
                ),
                (
                    "desktop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desk_image",
                        to="adaptive_images.imagepreset",
                    ),
                ),
                (
                    "mobile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mob_image",
                        to="adaptive_images.imagepreset",
                    ),
                ),
            ],
            options={
                "db_table": "adaptive_image_setting",
            },
        ),
        migrations.CreateModel(
            name="AdaptiveImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_compressed", models.BooleanField(default=False, verbose_name="compressed?")),
                (
                    "desktop",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desktop_images",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "mobile",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_images",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "original",
                    filer.fields.image.FilerImageField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_images",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="adaptive_images.adaptiveimagesetting",
                    ),
                ),
            ],
            options={
                "db_table": "adaptive_image",
            },
        ),
    ]
