# Generated by Django 4.2 on 2024-01-07 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_on_main_page",
        ),
    ]
