# Generated by Django 4.2 on 2024-01-07 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_remove_project_is_on_main_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="is_on_main_page",
        ),
    ]
