# Generated by Django 4.2 on 2024-01-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_remove_feedback_is_on_main_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
