# Generated by Django 4.2 on 2024-01-08 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="text",
            new_name="description",
        ),
    ]
